#include "core/managed/EntityInteropLayout.h"

#include "managed/interop/DotNetHost.h"

namespace cm::interop {

EntityInteropLayout BuildEntityInteropLayout() {
    EntityInteropLayout layout;
    layout.entityCoreCount = 35;
    layout.tweenCount = 7;
    layout.componentCount = 401;
    layout.moduleCount = 25;
    layout.sceneCount = 7;

    layout.args = {
        (void*)GetEntityWorldPositionPtr,
        (void*)SetEntityWorldPositionPtr,
        (void*)FindEntityByNamePtr,
        (void*)GetEntityNamePtr,
        (void*)GetEntitiesPtr,
        (void*)GetEntityCountPtr,
        (void*)CreateEntityPtr,
        (void*)DestroyEntityPtr,
        (void*)GetEntityByIDPtr,
        (void*)GetEntityRotationPtr,
        (void*)SetEntityRotationPtr,
        (void*)GetEntityRotationQuatPtr,
        (void*)SetEntityRotationQuatPtr,
        (void*)GetEntityScalePtr,
        (void*)SetEntityScalePtr,
        (void*)SetLinearVelocityPtr,
        (void*)SetAngularVelocityPtr,
        (void*)SetEntityVisiblePtr,
        (void*)GetEntityVisiblePtr,
        (void*)SetEntityPresentationHiddenPtr,
        (void*)GetEntityPresentationHiddenPtr,
        (void*)SetEntityActivePtr,
        (void*)GetEntityActivePtr,
        (void*)IsSceneBeingDestroyedPtr,
        (void*)GetEntityLocalPositionPtr,
        (void*)SetEntityLocalPositionPtr,
        // Parenting Interop (7 functions)
        (void*)SetEntityParentPtr,
        (void*)GetEntityParentPtr,
        (void*)GetEntityChildrenPtr,
        (void*)GetEntityChildCountPtr,
        (void*)FindChildByNamePtr,
        (void*)FindDescendantByNamePtr,
        (void*)CreateEntityWithParentPtr,
        // Duplication and UI mouse position
        (void*)DuplicateEntityPtr,
        (void*)GetUIMousePositionPtr,

        // Tween Interop (must match tweenCount)
        (void*)Tween_PositionPtr,
        (void*)Tween_RotationEulerPtr,
        (void*)Tween_ScalePtr,
        (void*)Tween_LightIntensityPtr,
        (void*)Tween_ManagedFloatPtr,
        (void*)Tween_ManagedVec3Ptr,
        (void*)Tween_SetFinishedCallbackPtr,

        // Component Interop (must match componentCount)
        (void*)ManagedLogPtr,
        (void*)HasComponentPtr,
        (void*)AddComponentPtr,
        (void*)RemoveComponentPtr,
        (void*)GetLightTypePtr,
        (void*)SetLightTypePtr,
        (void*)GetLightColorPtr,
        (void*)SetLightColorPtr,
        (void*)GetLightIntensityPtr,
        (void*)SetLightIntensityPtr,
        (void*)GetRigidBodyMassPtr,
        (void*)SetRigidBodyMassPtr,
        (void*)GetRigidBodyIsKinematicPtr,
        (void*)SetRigidBodyIsKinematicPtr,
        (void*)GetRigidBodyUseGravityPtr,
        (void*)SetRigidBodyUseGravityPtr,
        (void*)GetRigidBodyCollisionMaskPtr,
        (void*)SetRigidBodyCollisionMaskPtr,
        (void*)GetRigidBodyLinearVelocityPtr,
        (void*)SetRigidBodyLinearVelocityPtr,
        (void*)GetRigidBodyAngularVelocityPtr,
        (void*)SetRigidBodyAngularVelocityPtr,
        (void*)ApplyRigidBodyForcePtr,
        (void*)ApplyRigidBodyTorquePtr,
        (void*)ApplyRigidBodyImpulsePtr,
        (void*)ApplyRigidBodyAngularImpulsePtr,
        (void*)RigidBody_GetDebugSummaryPtr,
        (void*)Collider_GetOffsetPtr,
        // Camera layer mask
        (void*)GetCameraLayerMask,
        (void*)SetCameraLayerMask,
        (void*)Camera_SetLayerMaskByName,
        // Camera settings (12 entries)
        (void*)GetCameraActivePtr,
        (void*)SetCameraActivePtr,
        (void*)GetCameraPriorityPtr,
        (void*)SetCameraPriorityPtr,
        (void*)GetCameraFieldOfViewPtr,
        (void*)SetCameraFieldOfViewPtr,
        (void*)GetCameraNearClipPtr,
        (void*)SetCameraNearClipPtr,
        (void*)GetCameraFarClipPtr,
        (void*)SetCameraFarClipPtr,
        (void*)GetCameraIsPerspectivePtr,
        (void*)SetCameraIsPerspectivePtr,
        (void*)SetBlendShapeWeightPtr,
        (void*)GetBlendShapeWeightPtr,
        (void*)GetBlendShapeCountPtr,
        (void*)GetBlendShapeNamePtr,

        // Animator parameter setters/getters
        (void*)&Animator_SetBool,
        (void*)&Animator_SetInt,
        (void*)&Animator_SetFloat,
        (void*)&Animator_SetTrigger,
        (void*)&Animator_ResetTrigger,
        (void*)&Animator_GetBool,
        (void*)&Animator_GetInt,
        (void*)&Animator_GetFloat,
        (void*)&Animator_GetTrigger,
        (void*)&Animator_GetCurrentStateName,
        (void*)&Animator_GetEnabled,
        (void*)&Animator_SetEnabled,
        (void*)&Animator_SetController,
        (void*)&Animator_SetOverride,
        (void*)&Animator_GetCurrentClipRootMotionMode,
        (void*)&NpcScalability_GetParticipates,
        (void*)&NpcScalability_GetTier,
        (void*)&NpcScalability_GetRepresentation,
        (void*)&NpcScalability_GetReasonFlags,
        (void*)&NpcScalability_GetCameraDistance,
        (void*)&NpcScalability_GetVisible,
        (void*)&NpcScalability_GetCrowdRank,
        (void*)&NpcScalability_GetCrowdCount,
        (void*)&NpcScalability_GetAnimationUpdateInterval,
        (void*)&NpcScalability_GetScriptUpdateInterval,
        (void*)&NpcScalability_GetNavigationRepathInterval,

        // UI Buttons
        (void*)&UI_ButtonIsHovered,
        (void*)&UI_ButtonIsPressed,
        (void*)&UI_ButtonWasClicked,

        // Unified Morphs
        (void*)UnifiedMorph_GetCountPtr,
        (void*)UnifiedMorph_GetNamePtr,
        (void*)UnifiedMorph_GetWeightPtr,
        (void*)UnifiedMorph_SetWeightPtr,
        (void*)UnifiedMorph_PropagateAllPtr,

        // TintMaskController
        (void*)TintController_HasComponentPtr,
        (void*)TintController_GetNamePatternPtr,
        (void*)TintController_SetNamePatternPtr,
        (void*)TintController_GetBaseTintPtr,
        (void*)TintController_SetBaseTintPtr,
        (void*)TintController_GetTintColorPtr,
        (void*)TintController_SetTintColorPtr,
        (void*)TintController_GetUseTintMaskPtr,
        (void*)TintController_SetUseTintMaskPtr,
        (void*)TintController_GetUsePbrOverridesPtr,
        (void*)TintController_SetUsePbrOverridesPtr,
        (void*)TintController_GetPbrMetallicPtr,
        (void*)TintController_SetPbrMetallicPtr,
        (void*)TintController_GetPbrRoughnessPtr,
        (void*)TintController_SetPbrRoughnessPtr,
        (void*)TintController_GetPbrEmissionColorPtr,
        (void*)TintController_SetPbrEmissionColorPtr,
        (void*)TintController_GetPbrEmissionStrengthPtr,
        (void*)TintController_SetPbrEmissionStrengthPtr,
        (void*)TintController_GetGlobalBlendModePtr,
        (void*)TintController_SetGlobalBlendModePtr,
        (void*)TintController_GetAutoIncludeParentedSkinnedMeshesPtr,
        (void*)TintController_SetAutoIncludeParentedSkinnedMeshesPtr,
        (void*)TintController_RefreshPtr,
        (void*)TintController_ClearTargetsPtr,
        (void*)TintController_RemoveTargetsForEntityPtr,
        (void*)TintController_AddTargetPtr,
        (void*)TintController_GetTrackedTargetCountPtr,
        (void*)TintController_GetTrackedTargetEntityPtr,

        // BoneAttachment (19 entries)
        (void*)BoneAttachment_HasComponentPtr,
        (void*)BoneAttachment_GetEnabledPtr,
        (void*)BoneAttachment_SetEnabledPtr,
        (void*)BoneAttachment_GetBoneNamePtr,
        (void*)BoneAttachment_SetBoneNamePtr,
        (void*)BoneAttachment_GetLocalPositionPtr,
        (void*)BoneAttachment_SetLocalPositionPtr,
        (void*)BoneAttachment_GetLocalRotationPtr,
        (void*)BoneAttachment_SetLocalRotationPtr,
        (void*)BoneAttachment_GetLocalScalePtr,
        (void*)BoneAttachment_SetLocalScalePtr,
        (void*)BoneAttachment_GetInheritRotationPtr,
        (void*)BoneAttachment_SetInheritRotationPtr,
        (void*)BoneAttachment_GetInheritScalePtr,
        (void*)BoneAttachment_SetInheritScalePtr,
        (void*)BoneAttachment_IsResolvedPtr,
        (void*)BoneAttachment_InvalidateResolutionPtr,
        (void*)BoneAttachment_GetSkeletonEntityPtr,
        (void*)BoneAttachment_SetSkeletonEntityPtr,

        // Character Controller (7 entries)
        (void*)CC_SetDesiredVelocityPtr,
        (void*)CC_GetDesiredVelocityPtr,
        (void*)CC_SetVerticalVelocityPtr,
        (void*)CC_GetVerticalVelocityPtr,
        (void*)CC_JumpPtr,
        (void*)CC_IsGroundedPtr,
        (void*)CC_SetPositionPtr,
        // UI Text (42 entries)
        (void*)UI_Text_GetTextPtr,
        (void*)UI_Text_SetTextPtr,
        (void*)UI_Text_GetOpacityPtr,
        (void*)UI_Text_SetOpacityPtr,
        (void*)UI_Text_GetVisiblePtr,
        (void*)UI_Text_SetVisiblePtr,
        (void*)UI_Text_GetColorPtr,
        (void*)UI_Text_SetColorPtr,
        (void*)UI_Text_GetPixelSizePtr,
        (void*)UI_Text_SetPixelSizePtr,
        (void*)UI_Text_GetZOrderPtr,
        (void*)UI_Text_SetZOrderPtr,
        (void*)UI_Text_GetFontPathPtr,
        (void*)UI_Text_SetFontPathPtr,
        (void*)UI_Text_GetAnchorEnabledPtr,
        (void*)UI_Text_SetAnchorEnabledPtr,
        (void*)UI_Text_GetAnchorPtr,
        (void*)UI_Text_SetAnchorPtr,
        (void*)UI_Text_GetAnchorOffsetPtr,
        (void*)UI_Text_SetAnchorOffsetPtr,
        (void*)UI_Text_GetWordWrapPtr,
        (void*)UI_Text_SetWordWrapPtr,
        (void*)UI_Text_GetRectSizePtr,
        (void*)UI_Text_SetRectSizePtr,
        (void*)UI_Text_GetWorldSpacePtr,
        (void*)UI_Text_SetWorldSpacePtr,
        (void*)UI_Text_GetBillboardPtr,
        (void*)UI_Text_SetBillboardPtr,
        (void*)UI_Text_GetOutlineEnabledPtr,
        (void*)UI_Text_SetOutlineEnabledPtr,
        (void*)UI_Text_GetOutlineColorPtr,
        (void*)UI_Text_SetOutlineColorPtr,
        (void*)UI_Text_GetOutlineThicknessPtr,
        (void*)UI_Text_SetOutlineThicknessPtr,
        (void*)UI_Text_GetShadowEnabledPtr,
        (void*)UI_Text_SetShadowEnabledPtr,
        (void*)UI_Text_GetShadowColorPtr,
        (void*)UI_Text_SetShadowColorPtr,
        (void*)UI_Text_GetShadowOffsetPtr,
        (void*)UI_Text_SetShadowOffsetPtr,
        (void*)UI_Text_GetAlignmentPtr,
        (void*)UI_Text_SetAlignmentPtr,
        // UI Panel (34 entries)
        (void*)UI_Panel_GetOpacityPtr,
        (void*)UI_Panel_SetOpacityPtr,
        (void*)UI_Panel_GetVisiblePtr,
        (void*)UI_Panel_SetVisiblePtr,
        (void*)UI_Panel_GetSizePtr,
        (void*)UI_Panel_SetSizePtr,
        (void*)UI_Panel_GetTintColorPtr,
        (void*)UI_Panel_SetTintColorPtr,
        (void*)UI_Panel_GetAnchorEnabledPtr,
        (void*)UI_Panel_SetAnchorEnabledPtr,
        (void*)UI_Panel_GetAnchorPtr,
        (void*)UI_Panel_SetAnchorPtr,
        (void*)UI_Panel_GetAnchorOffsetPtr,
        (void*)UI_Panel_SetAnchorOffsetPtr,
        (void*)UI_Panel_GetAnchorToParentPtr,
        (void*)UI_Panel_SetAnchorToParentPtr,
        (void*)UI_Panel_GetZOrderPtr,
        (void*)UI_Panel_SetZOrderPtr,
        (void*)UI_Panel_IsHoveredPtr,
        (void*)UI_Panel_IsPressedPtr,
        (void*)UI_Panel_IsDraggingPtr,
        (void*)UI_Panel_DragStartedPtr,
        (void*)UI_Panel_DragEndedPtr,
        (void*)UI_Panel_WasDroppedPtr,
        (void*)UI_Panel_GetDropSourcePtr,
        (void*)UI_Panel_GetDropTargetPtr,
        (void*)UI_Panel_GetAllowDragPtr,
        (void*)UI_Panel_SetAllowDragPtr,
        (void*)UI_Panel_GetAllowDropPtr,
        (void*)UI_Panel_SetAllowDropPtr,
        (void*)UI_Panel_SetTexturePtr,
        (void*)UI_Panel_GetTexturePtr,
        (void*)UI_Panel_GetDriveChildrenOpacityPtr,
        (void*)UI_Panel_SetDriveChildrenOpacityPtr,

        // UI Rect (12 entries)
        (void*)UI_Rect_GetAnchorToParentPtr,
        (void*)UI_Rect_SetAnchorToParentPtr,
        (void*)UI_Rect_GetHorizontalAnchorPtr,
        (void*)UI_Rect_SetHorizontalAnchorPtr,
        (void*)UI_Rect_GetVerticalAnchorPtr,
        (void*)UI_Rect_SetVerticalAnchorPtr,
        (void*)UI_Rect_GetPivotPtr,
        (void*)UI_Rect_SetPivotPtr,
        (void*)UI_Rect_GetOffsetPtr,
        (void*)UI_Rect_SetOffsetPtr,
        (void*)UI_Rect_GetSizePtr,
        (void*)UI_Rect_SetSizePtr,
        // UI Canvas (6 entries)
        (void*)UI_Canvas_GetOpacityPtr,
        (void*)UI_Canvas_SetOpacityPtr,
        (void*)UI_Canvas_GetRenderSpacePtr,
        (void*)UI_Canvas_SetRenderSpacePtr,
        (void*)UI_Canvas_GetBillboardPtr,
        (void*)UI_Canvas_SetBillboardPtr,

        // UI LayoutGroup (16 entries)
        (void*)UI_LayoutGroup_GetDirectionPtr,
        (void*)UI_LayoutGroup_SetDirectionPtr,
        (void*)UI_LayoutGroup_GetPaddingPtr,
        (void*)UI_LayoutGroup_SetPaddingPtr,
        (void*)UI_LayoutGroup_GetSpacingPtr,
        (void*)UI_LayoutGroup_SetSpacingPtr,
        (void*)UI_LayoutGroup_GetChildAlignmentPtr,
        (void*)UI_LayoutGroup_SetChildAlignmentPtr,
        (void*)UI_LayoutGroup_GetCrossAlignmentPtr,
        (void*)UI_LayoutGroup_SetCrossAlignmentPtr,
        (void*)UI_LayoutGroup_GetControlChildWidthPtr,
        (void*)UI_LayoutGroup_SetControlChildWidthPtr,
        (void*)UI_LayoutGroup_GetControlChildHeightPtr,
        (void*)UI_LayoutGroup_SetControlChildHeightPtr,
        (void*)UI_LayoutGroup_GetReverseOrderPtr,
        (void*)UI_LayoutGroup_SetReverseOrderPtr,

        // UI FitToContent (14 entries)
        (void*)UI_FitToContent_GetEnabledPtr,
        (void*)UI_FitToContent_SetEnabledPtr,
        (void*)UI_FitToContent_GetFitWidthPtr,
        (void*)UI_FitToContent_SetFitWidthPtr,
        (void*)UI_FitToContent_GetFitHeightPtr,
        (void*)UI_FitToContent_SetFitHeightPtr,
        (void*)UI_FitToContent_GetPaddingPtr,
        (void*)UI_FitToContent_SetPaddingPtr,
        (void*)UI_FitToContent_GetMinSizePtr,
        (void*)UI_FitToContent_SetMinSizePtr,
        (void*)UI_FitToContent_GetMaxSizePtr,
        (void*)UI_FitToContent_SetMaxSizePtr,
        (void*)UI_FitToContent_GetDirectChildrenOnlyPtr,
        (void*)UI_FitToContent_SetDirectChildrenOnlyPtr,

        // UI Scene Capture (30 entries)
        (void*)UI_SceneCapture_GetEnabledPtr,
        (void*)UI_SceneCapture_SetEnabledPtr,
        (void*)UI_SceneCapture_GetAutoFramePtr,
        (void*)UI_SceneCapture_SetAutoFramePtr,
        (void*)UI_SceneCapture_GetIncludeChildrenPtr,
        (void*)UI_SceneCapture_SetIncludeChildrenPtr,
        (void*)UI_SceneCapture_GetBoundsPaddingPtr,
        (void*)UI_SceneCapture_SetBoundsPaddingPtr,
        (void*)UI_SceneCapture_GetFieldOfViewPtr,
        (void*)UI_SceneCapture_SetFieldOfViewPtr,
        (void*)UI_SceneCapture_GetNearClipPtr,
        (void*)UI_SceneCapture_SetNearClipPtr,
        (void*)UI_SceneCapture_GetFarClipPtr,
        (void*)UI_SceneCapture_SetFarClipPtr,
        (void*)UI_SceneCapture_GetViewDirectionPtr,
        (void*)UI_SceneCapture_SetViewDirectionPtr,
        (void*)UI_SceneCapture_GetUpDirectionPtr,
        (void*)UI_SceneCapture_SetUpDirectionPtr,
        (void*)UI_SceneCapture_GetFocusOffsetPtr,
        (void*)UI_SceneCapture_SetFocusOffsetPtr,
        (void*)UI_SceneCapture_GetTargetEntityPtr,
        (void*)UI_SceneCapture_SetTargetEntityPtr,
        (void*)UI_SceneCapture_GetRenderSizePtr,
        (void*)UI_SceneCapture_SetRenderSizePtr,
        (void*)UI_SceneCapture_GetClearColorPtr,
        (void*)UI_SceneCapture_SetClearColorPtr,
        (void*)UI_SceneCapture_GetShowGridPtr,
        (void*)UI_SceneCapture_SetShowGridPtr,
        (void*)UI_SceneCapture_GetLockViewToTargetPtr,
        (void*)UI_SceneCapture_SetLockViewToTargetPtr,

        // UI Slider (9 entries)
        (void*)UI_Slider_GetValuePtr,
        (void*)UI_Slider_SetValuePtr,
        (void*)UI_Slider_GetMinValuePtr,
        (void*)UI_Slider_SetMinValuePtr,
        (void*)UI_Slider_GetMaxValuePtr,
        (void*)UI_Slider_SetMaxValuePtr,
        (void*)UI_Slider_IsHoveredPtr,
        (void*)UI_Slider_IsDraggingPtr,
        (void*)UI_Slider_ValueChangedPtr,

        // UI ProgressBar (10 entries)
        (void*)UI_ProgressBar_GetValuePtr,
        (void*)UI_ProgressBar_SetValuePtr,
        (void*)UI_ProgressBar_GetMinValuePtr,
        (void*)UI_ProgressBar_SetMinValuePtr,
        (void*)UI_ProgressBar_GetMaxValuePtr,
        (void*)UI_ProgressBar_SetMaxValuePtr,
        (void*)UI_ProgressBar_GetOpacityPtr,
        (void*)UI_ProgressBar_SetOpacityPtr,
        (void*)UI_ProgressBar_GetVisiblePtr,
        (void*)UI_ProgressBar_SetVisiblePtr,

        // UI Toggle (5 entries)
        (void*)UI_Toggle_GetIsOnPtr,
        (void*)UI_Toggle_SetIsOnPtr,
        (void*)UI_Toggle_IsHoveredPtr,
        (void*)UI_Toggle_IsPressedPtr,
        (void*)UI_Toggle_ValueChangedPtr,

        // UI ScrollView (8 entries)
        (void*)UI_ScrollView_GetContentOffsetPtr,
        (void*)UI_ScrollView_SetContentOffsetPtr,
        (void*)UI_ScrollView_GetContentSizePtr,
        (void*)UI_ScrollView_SetContentSizePtr,
        (void*)UI_ScrollView_GetOpacityPtr,
        (void*)UI_ScrollView_SetOpacityPtr,
        (void*)UI_ScrollView_GetVisiblePtr,
        (void*)UI_ScrollView_SetVisiblePtr,

        // UI InputField (6 entries)
        (void*)UI_InputField_GetTextPtr,
        (void*)UI_InputField_SetTextPtr,
        (void*)UI_InputField_GetPlaceholderPtr,
        (void*)UI_InputField_SetPlaceholderPtr,
        (void*)UI_InputField_IsFocusedPtr,
        (void*)UI_InputField_TextChangedPtr,

        // UI Dropdown (9 entries)
        (void*)UI_Dropdown_GetSelectedIndexPtr,
        (void*)UI_Dropdown_SetSelectedIndexPtr,
        (void*)UI_Dropdown_GetOptionCountPtr,
        (void*)UI_Dropdown_GetOptionPtr,
        (void*)UI_Dropdown_SetOptionPtr,
        (void*)UI_Dropdown_AddOptionPtr,
        (void*)UI_Dropdown_ClearOptionsPtr,
        (void*)UI_Dropdown_IsOpenPtr,
        (void*)UI_Dropdown_SelectionChangedPtr,

        // Animation Layers (28 entries)
        (void*)&AnimLayer_GetOrCreate,
        (void*)&AnimLayer_Remove,
        (void*)&AnimLayer_Has,
        (void*)&AnimLayer_GetCount,
        (void*)&AnimLayer_GetNameByIndex,
        (void*)&AnimLayer_SetAnimation,
        (void*)&AnimLayer_GetAnimation,
        (void*)&AnimLayer_SetMask,
        (void*)&AnimLayer_GetMask,
        (void*)&AnimLayer_SetBlendMode,
        (void*)&AnimLayer_GetBlendMode,
        (void*)&AnimLayer_SetWeight,
        (void*)&AnimLayer_GetWeight,
        (void*)&AnimLayer_BlendTo,
        (void*)&AnimLayer_Play,
        (void*)&AnimLayer_Stop,
        (void*)&AnimLayer_IsPlaying,
        (void*)&AnimLayer_SetSpeed,
        (void*)&AnimLayer_GetSpeed,
        (void*)&AnimLayer_SetTime,
        (void*)&AnimLayer_SetNormalizedTime,
        (void*)&AnimLayer_SetState,
        (void*)&AnimLayer_SetStateByName,
        (void*)&AnimLayer_SetBlend2D,
        (void*)&AnimLayer_GetTime,
        (void*)&AnimLayer_GetDuration,
        (void*)&AnimLayer_SetLooping,
        (void*)&AnimLayer_GetLooping,

        // Terrain (12 entries)
        (void*)Terrain_GetHeightAtWorldPtr,
        (void*)Terrain_GetNormalAtWorldPtr,
        (void*)Terrain_GetNearestPointPtr,
        (void*)Terrain_RaycastPtr,
        (void*)Terrain_GetDominantLayerAtWorldPtr,
        (void*)Terrain_SetHeightAtWorldPtr,
        (void*)Terrain_ApplyHeightDeltaPtr,
        (void*)Terrain_GetInstancerLayerCountPtr,
        (void*)Terrain_GetInstancerLayerNamePtr,
        (void*)Terrain_SetInstancerLayerEnabledPtr,
        (void*)Terrain_SetInstancerLayerDensityPtr,
        (void*)Terrain_RegenerateInstancersPtr,

        // Spline (6 entries)
        (void*)Spline_GetControlPointCountPtr,
        (void*)Spline_GetControlPointPtr,
        (void*)Spline_GetSampledPointCountPtr,
        (void*)Spline_GetSampledPointPtr,
        (void*)Spline_GetNearestPointPtr,
        (void*)Spline_GetPointAtNormalizedPtr,

        // Portal (18 entries)
        (void*)Portal_GetEnabledPtr,
        (void*)Portal_SetEnabledPtr,
        (void*)Portal_GetTargetScenePathPtr,
        (void*)Portal_SetTargetScenePathPtr,
        (void*)Portal_GetTargetPortalGuidPtr,
        (void*)Portal_SetTargetPortalGuidPtr,
        (void*)Portal_GetTargetPortalPathPtr,
        (void*)Portal_SetTargetPortalPathPtr,
        (void*)Portal_GetEntryOffsetPtr,
        (void*)Portal_SetEntryOffsetPtr,
        (void*)Portal_GetExitOffsetPtr,
        (void*)Portal_SetExitOffsetPtr,
        (void*)Portal_GetAutoDetectPtr,
        (void*)Portal_SetAutoDetectPtr,
        (void*)Portal_GetTriggerRadiusPtr,
        (void*)Portal_SetTriggerRadiusPtr,
        (void*)Portal_GetFireExitEventsPtr,
        (void*)Portal_SetFireExitEventsPtr,

        // Module Component Interop (25 entries)
        (void*)HasModuleComponentPtr,
        (void*)AddModuleComponentPtr,
        (void*)RemoveModuleComponentPtr,
        (void*)GetModuleComponentPtr,
        (void*)GetModuleComponentByFullNamePtr,
        (void*)GetModuleFieldBoolPtr,
        (void*)GetModuleFieldIntPtr,
        (void*)GetModuleFieldInt64Ptr,
        (void*)GetModuleFieldFloatPtr,
        (void*)GetModuleFieldDoublePtr,
        (void*)GetModuleFieldStringPtr,
        (void*)GetModuleFieldVec2Ptr,
        (void*)GetModuleFieldVec3Ptr,
        (void*)GetModuleFieldVec4Ptr,
        (void*)GetModuleFieldQuatPtr,
        (void*)SetModuleFieldBoolPtr,
        (void*)SetModuleFieldIntPtr,
        (void*)SetModuleFieldInt64Ptr,
        (void*)SetModuleFieldFloatPtr,
        (void*)SetModuleFieldDoublePtr,
        (void*)SetModuleFieldStringPtr,
        (void*)SetModuleFieldVec2Ptr,
        (void*)SetModuleFieldVec3Ptr,
        (void*)SetModuleFieldVec4Ptr,
        (void*)SetModuleFieldQuatPtr,
        // Scene interop (7 trailing)
        (void*)Scene_LoadScene,
        (void*)Scene_UnloadScene,
        (void*)Scene_LoadSceneEx,
        (void*)Scene_GetLoadProgress,
        (void*)Scene_IsSceneLoading,
        (void*)Scene_IsSceneLoaded,
        (void*)Scene_GetCurrentScenePath
    };

    return layout;
}

int GetExpectedEntityInteropTotal(const EntityInteropLayout& layout) {
    return layout.entityCoreCount + layout.tweenCount + layout.componentCount
        + layout.moduleCount + layout.sceneCount;
}

} // namespace cm::interop
