#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <glm/glm.hpp>

// Common binary format definitions for Claymore assets
// These are the runtime-loadable formats generated by the editor

namespace binary {

// Magic numbers for format identification
constexpr uint32_t SCENE_MAGIC = 'S' | ('C' << 8) | ('N' << 16) | ('B' << 24);    // 'SCNB'
constexpr uint32_t MATERIAL_MAGIC = 'M' | ('A' << 8) | ('T' << 16) | ('B' << 24); // 'MATB'
constexpr uint32_t PREFAB_MAGIC = 'P' | ('R' << 8) | ('F' << 16) | ('B' << 24);   // 'PRFB'
constexpr uint32_t ANIM_CTRL_MAGIC = 'A' | ('C' << 8) | ('T' << 16) | ('B' << 24); // 'ACTB'

// Current format versions
constexpr uint32_t SCENE_VERSION = 30;  // v30 persists tint-mask inline PBR state
constexpr uint32_t MATERIAL_VERSION = 1;
constexpr uint32_t PREFAB_VERSION = 30;  // v30 persists tint-mask inline PBR state
constexpr uint32_t ANIM_CTRL_VERSION = 1;
constexpr uint32_t MODEL_DELTA_VERSION = 1;

// Common header for all binary assets
struct BinaryAssetHeader {
    uint32_t magic;
    uint32_t version;
    uint32_t flags;
    uint32_t reserved;
};

// Scene binary header
struct SceneBinaryHeader {
    BinaryAssetHeader base;
    uint32_t entityCount;
    uint32_t componentTableOffset;
    uint32_t stringTableOffset;
    uint32_t assetRefTableOffset;
    uint32_t environmentOffset;     // Offset to environment data (v2+)
    uint32_t environmentSize;       // Size of environment data block
    uint32_t modelDeltaTableOffset; // Offset to model deltas table (v3+)
    uint32_t modelDeltaCount;       // Number of model deltas (v3+)
};

// Model delta reference entry (for scene binary)
// The actual delta data is stored as JSON blob for flexibility
struct ModelDeltaEntry {
    uint64_t modelGuidHigh;     // Model asset GUID
    uint64_t modelGuidLow;
    uint32_t rootEntityId;      // Entity ID of model root in scene
    uint32_t dataOffset;        // Offset to delta data blob
    uint32_t dataSize;          // Size of delta data blob
};

// Material binary header
struct MaterialBinaryHeader {
    BinaryAssetHeader base;
    uint32_t shaderNameOffset;      // Offset to shader name in string table
    uint32_t textureCount;
    uint32_t uniformCount;
    uint32_t textureTableOffset;
    uint32_t uniformTableOffset;
    uint32_t stringTableOffset;
};

// Prefab binary header
struct PrefabBinaryHeader {
    BinaryAssetHeader base;
    uint32_t entityCount;
    uint32_t rootEntityIndex;
    uint32_t componentTableOffset;
    uint32_t stringTableOffset;
    uint32_t assetRefTableOffset;
    uint32_t modelDeltaTableOffset; // Offset to model deltas table (v3+)
    uint32_t modelDeltaCount;       // Number of model deltas (v3+)
};

// Component type IDs for binary serialization
enum class ComponentTypeId : uint16_t {
    None = 0,
    Transform,
    Mesh,
    MeshProxy,
    Light,
    Camera,
    Skeleton,
    Skinning,
    BlendShape,
    Collider,
    RigidBody,
    StaticBody,
    CharacterController,
    Terrain,
    ParticleEmitter,
    Canvas,
    Panel,
    Button,
    Text,
    NavMesh,
    NavAgent,
    NavLink,
    AnimationPlayer,
    RenderOverrides,
    Area,
    Script,
    Module,
    // Additional components for full parity with JSON serializer
    BoneAttachment,
    UnifiedMorph,
    TintController,
    GrassDeformer,
    River,
    Spline,
    Slider,
    ProgressBar,
    Toggle,
    ScrollView,
    LayoutGroup,
    InputField,
    Dropdown,
    IKConstraint,
    LookAtConstraint,
    Instancer,
    UIRect,
    FitToContent,
    UISceneCapture,
    ResourceLayers,
    Portal,
    Softbody,
    AudioSource,
    AudioListener,
    MAX_COMPONENT_TYPE
};

// Binary component entry header
struct ComponentEntry {
    ComponentTypeId typeId;
    uint16_t flags;
    uint32_t dataSize;
    uint32_t dataOffset;
};

// String table entry
struct StringEntry {
    uint32_t offset;
    uint32_t length;
};

// Asset reference entry (for resolving paths to GUIDs at load time)
struct AssetRefEntry {
    uint64_t guidHigh;
    uint64_t guidLow;
    uint32_t pathOffset;  // Offset into string table
    uint32_t typeHint;    // What kind of asset (material, mesh, texture, etc.)
};

// Texture reference in material
struct TextureSlotEntry {
    uint32_t slotId;          // e.g., 0=albedo, 1=normal, 2=metallicRoughness
    uint32_t pathOffset;      // String table offset
};

// Uniform entry in material
struct UniformEntry {
    uint32_t nameOffset;      // String table offset
    uint32_t type;            // 0=float, 1=vec2, 2=vec3, 3=vec4
    float data[4];            // Up to vec4
};

// Material type enum for inline materials
enum class InlineMaterialType : uint8_t {
    PBR = 0,
    PSX = 1,
    ShaderGraph = 2
};

// Inline material data (for materials embedded in scene, not separate .mat files)
struct InlineMaterialData {
    uint32_t slotIndex = 0;
    InlineMaterialType materialType = InlineMaterialType::PBR;
    
    // Common PBR texture paths
    std::string albedoPath;
    std::string metallicRoughnessPath;
    std::string normalPath;
    std::string aoPath;
    std::string emissionPath;
    std::string displacementPath;
    std::string tintMaskPath;
    
    // PBR scalar properties
    float metallic = 0.0f;
    float roughness = 0.5f;
    float normalScale = 1.0f;
    float aoStrength = 1.0f;
    float emissionStrength = 0.0f;
    float displacementScale = 0.0f;
    glm::vec3 emissionColor = glm::vec3(1.0f);
    glm::vec2 uvScale = glm::vec2(1.0f);
    glm::vec2 uvOffset = glm::vec2(0.0f);
    glm::vec4 tint = glm::vec4(1.0f);
    bool hasAlpha = false;
    bool receiveShadowsOverride = false;
    bool receiveShadows = false;
    
    // PSX material properties (when materialType == PSX)
    glm::vec4 psxParams = glm::vec4(0.0f);     // u_psxParams
    glm::vec4 psxWorld = glm::vec4(0.0f, 0.25f, 0.0f, 0.0f);  // u_psxWorld
    glm::vec4 toonParams = glm::vec4(3.0f, 1.0f, 0.0f, 0.0f); // u_toonParams
    
    // Shader graph properties (when materialType == ShaderGraph)
    std::string shaderGraphPath;
    std::string shaderGraphName;
    uint64_t stateFlags = 0;
};

// Shader graph material parameter for binary serialization
struct ShaderGraphParamData {
    std::string name;
    std::string displayName;
    uint32_t type = 0;  // ShaderValueType as int
    glm::vec4 value = glm::vec4(0.0f);
    std::string texturePath;
    int32_t textureSlot = -1;
};

// Extended inline material data for shader graph (separate to avoid bloating InlineMaterialData)
struct ShaderGraphMaterialData {
    uint32_t slotIndex = 0;
    std::string shaderGraphPath;
    std::string name;
    std::string compiledVSName;   // e.g., "vs_shgraph_MyShader" - for runtime loading
    std::string compiledFSName;   // e.g., "fs_shgraph_MyShader" - for runtime loading
    glm::vec2 uvScale = glm::vec2(1.0f);
    glm::vec2 uvOffset = glm::vec2(0.0f);
    uint64_t stateFlags = 0;
    bool twoSided = false;
    bool alphaClip = false;
    float alphaClipThreshold = 0.5f;
    std::vector<ShaderGraphParamData> parameters;
};

} // namespace binary


